### ISSUE TITLE
License not clear

### ISSUE THREAD

**Issue by ChristophWurst** [invokr/docker-mail#1]
Hi @invokr,
is this project licensed free software? In other words is it ok that I created [a fork](https://github.com/ChristophWurst/owncloud-mail-test-docker) of this repo that we're using to test the ownCloud Mail app? :smile: 
I couldn't neither find information in the readme, nor a license file.
Christoph

**Comment by invokr** [comment]
Hi @ChristophWurst,

thanks for making me aware of the missing license, this is probably true for all my docker repos. I will add the correct licenses later this week. Feel free to use the container under the public domain or MIT license :smile: 

On another note: I disabled a couple of old cyphers in wake of the drown attack. The configuration wasn't insecure but it's better to be safe than sorry. I recommend you merge the last two commits. 

Rob

**Comment by ChristophWurst** [comment]
Hi @invokr 
awesome, thanks for sharing this awesome docker image. Although we're using the image for testing purposes only, I'll consider merging those commits. Thanks for the note.
Christoph
